web:
    build: web
    ports:
    - "8080:80"
    - "3306:3306"
    volumes:
    - "$PWD/../trunk/:/opt/teddy/webapp"
    - "/var/log/teddy:/var/log/teddy"
    - "/usr/teddy/codigos:/usr/teddy/codigos"
    - "/usr/teddy/casos:/usr/teddy/casos"
    - "/var/log/nginx:/var/log/nginx"

runner:
    build: runner
    volumes:
    - "$PWD/../runner/bin:/opt/teddy/runner/bin"
    - "$PWD/../runner/lib:/opt/teddy/runner/lib"
    - "/var/log/teddy:/var/log/teddy"
    - "/usr/teddy/codigos:/usr/teddy/codigos"
    - "/usr/teddy/casos:/usr/teddy/casos"
    links:
    - web

