web:
    build: web
    ports:
    - "8080:80"
    - "3306:3306"
    volumes:
    - "$PWD/../trunk/serverside/controllers:/opt/teddy/trunk/serverside/controllers"
    - "$PWD/../trunk/www:/opt/teddy/trunk/www"
    - "/var/log/teddy:/var/log/teddy"

runner:
    build: runner
    volumes:
    - "$PWD/../trunk/codigos:/opt/teddy/trunk/codigos"
    - "$PWD/../trunk/work_zone:/opt/teddy/trunk/work_zone"
    - "$PWD/../runner/bin:/opt/teddy/runner/bin"
    - "$PWD/../runner/lib:/opt/teddy/runner/lib"
    - "/var/log/teddy:/var/log/teddy"
    links:
    - web

